<?php
if (is_null($this->session->get("admin"))) {
    $this->response->redirect("admin");
} else {
?>

<body>
    <?php include 'components/header.phtml'; ?>
    <?php include 'components/sidebar.phtml'; ?>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>



      <?php
      if($this->flashSession->output() !== null) {
        echo $this->flashSession->output();
      }
      ?>

      <h2 id="title">All Users</h2>
      <div class="table-responsive" id="section">
        <table class='table table-striped table-sm'>
              <thead>
                <tr>
                  <th scope='col'>User ID</th>
                  <th scope='col'>User Name</th>
                  <th scope='col'>Full Name</th>
                  <th scope='col'>Email</th>
                  <th scope='col'>Status</th>
                  <th scope='col'>Registeration Date</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>      
            <?php
            foreach ($users as $user) {
                ?>
                  <tr>
                    <td><?= $user->user_id; ?></td>
                    <td><?= $user->username; ?></td>
                    <td><?= $user->fullname; ?></td>
                    <td><?= $user->email; ?></td>
                    <td>

                    <?php
                        switch ($user->status) {
                            case 'Pending':
                            case "pending":
                                $select = "<option value='" . $user->status . "' selected> " . $user->status . "</option> 
                                               <option value='approved'>approved</option>
                                               <option value='not approved'>not approved</option>";
                                break;
                            case "Approved":
                            case "approved":
                                $select = "<option value='" . $user->status . "' selected> " . $user->status . "</option> 
                                                   <option value='pending'>pending</option>
                                                   <option value='not approved'>not approved</option>";
                                break;
                            case "Not approved":
                            case "not approved":
                                $select = "<option value='" . $user->status . "' selected> " . $user->status . "</option> 
                                                       <option value='approved'>approved</option>
                                                       <option value='pending'>pending</option>";
                                break;
                        }
                    ?>
                    <?= $this->tag->form(["admin/userStatus", "class" => "form"]) ?>
                    <?= $this->tag->hiddenField(["id", "value" => $user->user_id]) ?>
                        <select name="status" onchange="this.form.submit()">
                            <?=$select ?>
                        </select>
                    </form>
                    </td>
                    <td><?= $user->reg_date; ?></td>
                    <td>
                        <?= $this->tag->form(["admin/deleteuser", 'class'=>"form"]) ?>
                            <?= $this->tag->hiddenField(["id", "value" => $user->user_id]) ?>
                            <?= $this->tag->submitButton(["DELETE", "class" => "btn btn-danger"]) ?>
                        </form>
                    </td>
                  </tr>
                <?php 
            }
            ?>
              </tbody>
        </table>
      </div>
    </main>
    </div>
    </div>
   
</body>
<?php

}

