<?= $this->tag->getDoctype() ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $this->tag->getTitle(); ?></title>
    <?php echo $this->tag->stylesheetLink('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', false); ?>
</head>
<body>
    <div class="container">

    <div class="w-75 border m-auto py-4 bg-light rounded shadow">
    <h2 class="text-center my-4">Create Account</h2> 
    <?php echo $this->flashSession->output(); ?>
    <?php echo $this->tag->form(["signup/register", "class"=>"w-100 form m-3"]); ?>
    <table class="m-auto">
        <tr>
        <td> <label for="username">User Name</label></td>
        <td> <?php echo $form->render("username"); ?></td>
    </tr>


        <tr>
            <td><label for="fullname ">Full Name</label></td>
            <td><?php echo $form->render("fullname"); ?></td>
    </tr>

        <tr>
            <td><label for="email">EMail</label></td>
            <td><?php echo $form->render("email"); ?></td>
    </tr>

    <tr>
        <td> <label for="password">Password</label></td>
        <td><?php echo $form->render("password"); ?></td>
    </tr>
    <tr>
        <td> <label for="confirmpassword">Password</label></td>
        <td><?php echo $form->render("confirmpassword"); ?></td>
    </tr>
    <tr>
            <td><label for="mobile">Phone Number</label></td>
            <td><?php echo $form->render("mobile"); ?></td>
    </tr>
    <tr>
            <td><label for="address">Address</label></td>
            <td><?php echo $form->render("address"); ?></td>
    </tr>
    <tr>
            <td><label for="state">State</label></td>
            <td><?php echo $form->render("state"); ?></td>
    </tr>
    <tr>
            <td><label for="country">Country</label></td>
            <td><?php echo $form->render("country"); ?></td>
    </tr>
    

        <tr>
            <td></td>
        <td> <?php echo $this->tag->submitButton(["Register", "class"=>"btn btn-info"]);  ?></td>
    </tr>
    </table>
    </form>
    <p class="text-center"><?php echo "Have account? ". $this->tag->linkTo(["login", "Login Here!", 'class' => 'link'])."  "; ?></p>
    </div>
</div>

</body>

</html>