<?php
if (!$this->session->has("user")) {
    $this->response->redirect("login");
} else {
    $user = $this->session->get("user");
?>
    <?= $this->tag->getDoctype() ?>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <title><?= $this->tag->getTitle(); ?></title>
        <?php echo $this->tag->stylesheetLink('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', false); ?>
    </head>

    <body>
        <div class="container-fluid">
                     
            <div class="m-auto">
            <?php
            echo $this->tag->linkTo(["/", "Home", "class" => "btn btn-info"]);
            echo " ";
            echo $this->tag->linkTo(["login/logout", "Logout", "class" => "btn btn-danger"]);
            ?>
            </div>

            <h1 class='text-center'>Welcome <?php echo $this->session->user->username; ?> </h1>

            <!-- navbar -->
            <nav class="navbar navbar-expand-sm bg-info navbar-light">
            <div class="container-fluid">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" data-bs-toggle="collapse" data-bs-target="#profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="collapse" data-bs-target="#orders">My Orders</a>
                </li>
                
                        </div>
            </nav>
            
            <div id="accordion">

            <div id="profile" class="collapse show" data-bs-parent="#accordion">
            <?= $this->tag->form(["user/updateprofile", "class"=>"form"]) ?>
            <?php echo $this->flashSession->output(); ?>
               <table class="table p-3" id="table">
                   <tr>
                       <th class="w-25">Username</th>
                       <td><?= $this->tag->hiddenField(["id", "value"=>$user->user_id]) ?><?= $this->tag->textField(["username", "value"=>$user->username, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                   <th class="w-25">Fullname</th>
                       <td><?= $this->tag->textField(["fullname", "value"=>$user->fullname, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                   <th class="w-25">Email</th>
                       <td><?= $this->tag->textField(["email", "value"=>$user->email, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                   <th class="w-25">Phone Number</th>
                       <td><?= $this->tag->textField(["phone", "value"=>$user->phone, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                   <th class="w-25">Address</th>
                       <td><?= $this->tag->textArea(["address", "value"=>$user->address, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                        <th class="w-25">State</th>
                       <td><?= $this->tag->textField(["state", "value"=>$user->state, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   <tr>
                        <th class="w-25">Country</th>
                       <td><?= $this->tag->textField(["country", "value"=>$user->country, "disabled"=>"true", "class"=>"form-control"]) ?></td>
                   </tr>
                   </tr>
                   <tr>
                        <th class="w-25"></th>
                       <td><?=$this->tag->submitButton(["update", "value"=>"Update", "class"=>"btn btn-danger d-none", "id"=>"update"]) ?><button id="edit" class="btn btn-success w-25">Edit</button></td>
                   </tr>
               </table>
            </form>
            </div>

            <div id="orders" class="collapse" data-bs-parent="#accordion">
                <p>
                    <?php
                    if (count($orders)==0) {
                        echo "<h1>No orders placed yet!!</h1>";
                    } else {
                        echo "<table class='table'>";
                        echo "<tr>
                                <th>Items</th>
                                <th>Total Price</th>
                                <th>Quantity</th>
                                <th>Status</th>
                                <th>Order Date</th>
                            </tr>";
                        foreach ($orders as $order) {
                            ?>
                                <tr>
                                    <td><?=$order->items ?></td>
                                    <td><?=$order->totalprice ?></td>
                                    <td><?=$order->quantity ?></td>
                                    <td><?=$order->status ?></td>
                                    <td><?=$order->order_date ?></td>
                                </tr>
                            <?php
                        }
                        echo "</table>";
                    }
                    ?>
                </p>
            </div>

            <div id="wishlist" class="collapse" data-bs-parent="#accordion">
                <p>Wishlist</p>
            </div>

        </div>
        </div>

        </div>
    </body>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="../../../public/assests/js/script.js"></script>
    </html>
<?php
}
