<div class="m-3">
    <div class="bg-light d-flex justify-content-between mb-3">
        <?= $this->tag->linkTo(["/", "Home", "class"=>"btn btn-success"]) ?>
        <?= $this->tag->linkTo(["user", "My Profile", "class"=>"btn btn-warning"]) ?>
    </div>
    <?php echo $this->flashSession->output(); ?>
    <?php
    if (count($cart)==0) {
        echo "<div class='text-center'>";
        echo "<h1>Cart is empty</h1>";
        echo $this->tag->linkTo(["/", "Add Items", "class"=>"btn btn-info"]);
        echo "</div>";
    } else { ?>
    <table class="table table-dark">
        <tr>
            <th>Cart ID</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Category</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
<?php
$total=0;
$totalquant= 0;
foreach($cart as $item) {
    foreach($products as $product) {
        if ($item->product_id == $product->product_sku) {
            $total = $total+ ($item->quantity*$product->price);
            $totalquant = $totalquant + $item->quantity;
            ?>
            <tr>
                <td><?=$item->cart_id ?></td>
                <td><?= $product->productname ?></td>
                <td><?= $product->price ?></td>
                <td><?= $product->category ?></td>
                <td><?=$item->quantity ?></td>
                <td><?= ($item->quantity*$product->price) ?></td>
            </tr>
            <?php
        }
    }
}

?>
<tr>
    <th colspan="4"></th>
    <th>Total Quantity</th>
    <th>Grand Total</th>
</tr>
 <tr>
            <td colspan=4></td>
            <td><?=$totalquant ?></td>
            <td><?=$total ?></td>
        </tr>
    </table>
    <div class="text-right">
    <?= $this->tag->form(["order"]) ?>
    <?= $this->tag->hiddenField(["total", "value"=>$total]) ?>
    <?= $this->tag->hiddenField(["quantity", "value"=>$totalquant]) ?>
    <?= $this->tag->hiddenField(["cart", "value"=>json_encode($cart)]) ?>
    <?= $this->tag->submitButton(["order", "value"=>"Place Order", "class"=>"btn btn-info"]) ?>
    </form>
    </div>
    <?php
        }
        ?>
</div>