<?= $this->tag->getDoctype() ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $this->tag->getTitle(); ?></title>
    <?php echo $this->tag->stylesheetLink('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', false); ?>
</head>
<body>
 <?php echo $this->getContent(); ?>   
 </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>
   
